{% set name = "routingpy" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nilsnolde/routingpy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 80126dc6c2d41cbd435380f0abca7a19a91ef5d04bdc3fc07e85f211a2a3fc2d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=6.2

  run:
    - python >={{ python_min }}
    - requests >=2.2.0,<3.0.0
  run_constrained:
    - shapely >=2.0.0,<3
    - ipykernel >=6.0.0,<7
    - matplotlib-base >=3.4.1,<4
    - contextily >=1.1.0,<2
    - geopandas >=0.8.2,<0.9.0
    - descartes >=1.0.0,<2

test:
  imports:
    - routingpy
    - routingpy.routers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/routingpy/
  summary: Python library to access all public routing, isochrones and matrix APIs in a consistent manner.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
    - synapticarbors
