{% set name = "routingpy" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/routingpy-{{ version }}.tar.gz
  sha256: 297425fccf8911aa19e73ae245c5cb6464f4674eeceb9f699891bcb5f9d1d089

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=0.12
  run:
    - python >={{ python_min }}
    - requests >=2.0.0,<3.0.0
  run_constrained:
    - pandas >=1.1.0,<2
    - folium >=0.11.0,<1
    - shapely >=1.7.0,<2
    - ipykernel >=5.3.4,<6

test:
  imports:
    - routingpy
    - routingpy.routers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/routingpy/
  summary: Python library to access all public routing, isochrones and matrix APIs in a consistent manner.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knaaptime
    - ickc
